[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.21"
solc_optimize = true
solc_optimize_runs = 200

remappings = [ "forge-std/=lib/forge-std/", "@chainlink/contracts/=lib/@chainlink/contracts/", "@openzeppelin/contracts/=lib/@openzeppelin/contracts/", "foundry-devops/=lib/foundry-devops/" ]
[fuzz]
runs = 1000

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = {key = "${ETHERSCAN_API_KEY}"}

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
